### ISSUE TITLE
Ajout règles de contribution

### ISSUE THREAD

**Issue by morgancrociati** [2020-2021-ECOM-INFO5-G04/App#4]
Dans un contexte de contribution, il serait probablement utile de préciser les règles de contributions:
- Convention de nommage des banches/commits/issue
- Quand est-ce qu'on merge ?
- Qui fait les merges et sur quelle branche ?

**Comment by AlexisROLLIN** [comment]
Merci pour tes conseils, nous partageons ton avis et sommes en train d'établir les conventions.
